// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230322215941_RemovalOfEmployeesTable")]
    partial class RemovalOfEmployeesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DataAccess.Data.ArchivalItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ArchivalItemImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ArchivalItemLongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivalItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivalItemShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArchivalItems");
                });
#pragma warning restore 612, 618
        }
    }
}
